language: go

go:
  - "1.12"

git:
  # Use a shallow clone to hopefully speed up builds.
  depth: 1

notifications:
  email:
    on_success: never

before_install:
  - travis_retry go get -u github.com/fsnotify/fsnotify
  - travis_retry go get -u github.com/stretchr/testify/require
  - travis_retry go get -u github.com/pkg/errors
  - travis_retry go get -u github.com/yosssi/ace
  - travis_retry go get -u golang.org/x/lint/golint
  - travis_retry go get -u golang.org/x/net/html
  - travis_retry go get -u gopkg.in/russross/blackfriday.v2
  - travis_retry go get -u gopkg.in/yaml.v2

script:
  # bail after a single failure anywhere in this sequence
  - set -e

  - make

  - set -e
