language: go

go:
  - "1.12"

git:
  # Use a shallow clone to hopefully speed up builds.
  depth: 1

notifications:
  email:
    on_success: never

script:
  # bail after a single failure anywhere in this sequence
  - set -e

  - make

  - set -e
