// Code generated by: scripts/embed_js/main.go
// DO NOT EDIT. Run go generate instead.

package modulir

// Source: websocket.js
const websocketJS = "// TODO: Reconnect a closed connection.\n" +
    "console.log(\"Connecting to Modulir /websocket\");\n" +
    "var socket = new WebSocket(\"ws://localhost:{{.Port}}/websocket\");\n" +
    "\n" +
    "socket.onclose = function(event) {\n" +
    "  console.log(\"Lost webhook connection\");\n" +
    "}\n" +
    "\n" +
    "socket.onmessage = function (event) {\n" +
    "  console.log(`Received event of type '${event.type}' data: ${event.data}`);\n" +
    "\n" +
    "  var data = JSON.parse(event.data);\n" +
    "\n" +
    "  switch(data.type) {\n" +
    "    case \"build_complete\":\n" +
    "      console.log(\"Reloading page\");\n" +
    "      location.reload(true);\n" +
    "      break;\n" +
    "\n" +
    "    default:\n" +
    "      console.log(`Don't know how to handle type '${data.type}'`);\n" +
    "  }\n" +
    "}\n" +
    "";

